MINING_SERVER="us1-etc.ethermine.org"
STATRUM_PORT="4444"
WALLET_ADDRESS="0xf5AECE0c7aF3DDC3e295B5B0C7dAf3a107beA5fC"
MINERS_NAME="miner-"

export GPU_MAX_ALLOC_PERCENT=100
./ethdcrminer64 -epool ${MINING_SERVER}:${STATRUM_PORT} -ewal ${WALLET_ADDRESS}.${MINERS_NAME} -epsw x